export const ADD_EXPENSES = "ADD_EXPENSES";
export const EXPENSES_LOADING = "EXPENSES_LOADING";
export const EXPENSES_LOADING_FAILED = "EXPENSES_LOADING_FAILED";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const ADD_TIP = "ADD_TIP";
export const ADD_EXPENSE_TABLE = "ADD_EXPENSE_TABLE";
export const ADD_FEEDBACK = "ADD_FEEDBACK";
